### ISSUE TITLE
IMU link orientation is inconsistent with the physical robot

### ISSUE THREAD

**Issue by G-Levine** [tasts-robots/upkie_description#2]
Currently the `imu` link is oriented such that +z points up, +y points right, and +x points backwards.
Per Upkie's physical design and the [pi3hat IMU coordinate convention](https://github.com/mjbots/pi3hat/blob/master/docs/reference.md#orientation), the correct orientation would have +z point down, +y point right, and +x point forwards.

**Comment by stephane-caron** [comment]
Thanks for opening this issue. It is confirmed, according to the pi3hat convention the IMU frame should be oriented this way:

<img src="https://user-images.githubusercontent.com/1189580/225028232-98918f3d-c944-42b5-a2a5-f3b8ad7aeb20.png" width=400>

**Comment by stephane-caron** [comment]
Should be fixed!


```
python examples/display_frames.py --only imu
```

<img src="https://user-images.githubusercontent.com/1189580/225044464-150a869d-9faf-4ad2-aef9-4d9bc3044546.png" width=300>

Make sure to install the latest description by ``pip install upkie_description --upgrade``.
